name: Feature request
description: Suggest an improvement for the Yongnuo YN360 integration
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
